### PR TITLE
initial reticle sprite created to replace cursor

### PR DESCRIPTION
**Pull request by SialasTripp**
Just wanted to add, wasn't sure on final implementation of the style of the reticle or anything. Just wanted to get it working. Also, it should be hiding the mouse cursor with the "window.setMouseCursorVisible(false);" line, but for the life of me can't get it to work right now. I've read online that it could be a system issue overriding the attempt to hide it, so please let me know if it's hidden for you guys.

### CODE REVIEW

**Comment by jtbradshaw** [comment]
There is a tiny black cursor that is still showing up for me.

**Comment by mwinant** [comment]
I would assume you wouldnt want to completely hide it otherwise you wouldn't be able to click "close" to end the program right?
________________________________

**Comment by SialasTripp** [comment]
Well, I believe it's supposed to be hidden when acting as the reticle in the game but as soon as you move it past the game window, the normal cursor should appear so you could then close it. I'm going to try to mess around and see if there's a fix.
________________________________

**Review by jtbradshaw — APPROVED** [review]
Still need to figure out how to remove cursor, but reticle looks great

**Pull request merged**
